### PR TITLE
add past offering entry for 2015 spring to 3110

### PR DESCRIPTION
**Pull request by TrevorEdwards**

### CODE REVIEW

**Comment by lidavidm** [comment]
Looks good, thank you!

**Comment by lidavidm** [comment]
Hey Trevor, I noticed that we never added you to the contributors list (whoops). Would you like to be added, and if so, how would you prefer your name be listed?

**Comment by TrevorEdwards** [comment]
Sure, Trevor Edwards is fine!

**Comment by lidavidm** [comment]
Thanks, it should be live in a few minutes!

**Pull request merged**
