### PR TITLE
Adding ISSA, URMC links & InfoSci classes

### PR DESCRIPTION
**Pull request by SHBelsky**
Added links to Information Science Student Association & Under-Represented Minorities in Computing pages

Fixed Women in Computing at Cornell link

Added Information Science class details

Fixed some minor bugs

### CODE REVIEW

**Comment by lidavidm** [comment]
Hey, sorry I didn't see this earlier! Thank you for the changes, I'll review it ASAP.

**Comment by lidavidm** [comment]
Hey Shea, looks good! Just one question - do the em dashes not work for you? I notice the commit is labelled 'bug fixing'. I'd like to keep the dash style consistent, but if it's not working/displaying then we need to investigate.

**Comment by SHBelsky** [comment]
I didn't know if those dashes were intentional or a mistake. I reverted them to how they were. Apologies for that.

**Comment by lidavidm** [comment]
No worries, thank you! This looks good, I will merge.

**Comment by lidavidm** [comment]
And it's live. Thank you again!

**Pull request merged**
