### PR TITLE
Web Design class information

### PR DESCRIPTION
**Pull request by SHBelsky**
Added more information on the three web design classes, INFO/CS 1300, 2300, and 3300.

### CODE REVIEW

**Comment by lidavidm** [comment]
Awesome! Looks good, thank you for being our first contributor :)

I'm going to start up a contributors list, how would you like your name to appear? (Totally optional, of course.)

**Comment by SHBelsky** [comment]
"Shea Hunter Belsky" would be great.

Also, I don't see a place to edit this in the GitHub, but the title of the home page says `UCCS Wiki`; I haven't heard the `UCCS` abbreviation before, so I don't know if it's definitely something Cornell related or leftover from something else.

**Comment by lidavidm** [comment]
Ah, it's just abbreviating "Unofficial Cornell CS Wiki", but I guess that's clear. Maybe we'll write it out instead.

**Comment by lidavidm** [comment]
Alright, you're on the [contributors list](http://cornellcswiki.gitlab.io/contributors.html). Thanks again!

(I've also adjusted the title.)

**Pull request merged**
