### PR TITLE
Remove mean/harsh comments

### PR DESCRIPTION
**Pull request by watsonacc**
Hopcroft is an excellent educator, and when you google his course, you should not find scathing and unprofessional reviews on the first page of results.

Thanks for contributing! Make sure to also edit contributors.md if you're not yet listed there and would like to be featured.

### CODE REVIEW

**Comment by rishi1999** [comment]
Thanks for the pull request.

While I sympathize with your concerns, and in particular, I do agree that the very first comment on the page is somewhat unprofessional, I think it would be against the goals of this wiki to censor other users. The wiki should reflect the honest opinions of the students on campus.

I am ok with removing the first comment, and you are free to add any positive comments that you want, but the rest of the reviews, while negative, I think are respectfully stated, so they should stay.

If you update your PR to only be removing the first comment, and not anything else, I will gladly approve it.

**Comment by rishi1999** [comment]
Just following up - if you want to update the PR as I explained above, I can approve it right away.

Alternatively, I can make the changes myself (I will assume that you are ok with this if you do not respond).

**Comment by watsonacc** [comment]
Hey rishi1999, sorry I didn't see this for a very long time - I think that is reasonable (and I'm technology illiterate so I don't know how to edit my own pull request - if you can make any edits you think are reasonable that would be great, thanks!

**Comment by rishi1999** [comment]
Sounds good -- I'll make the changes!

**Pull request closed without merging**
