### PR TITLE
Add math classes

### PR DESCRIPTION
**Pull request by louisel**
Add list of math classes that are required or of interest, and pages for required and sometimes required math classes.

### CODE REVIEW

**Comment by lidavidm** [comment]
Hey Louise, thanks for the contribution! I like that you filled in info for both Arts & Sciences and Engineering. However, looks like there's some encoding issues. The em dashes in `classes/MATHRequired.md` and `classes/MATHSometimes.md` aren't in UTF-8, and our wiki software only accepts UTF-8, unfortunately. Would you mind fixing them?

They show up fine in Github, but if you look at the [raw output](https://raw.githubusercontent.com/louisel/CornellCSWiki/3386b0ba7726fe2447c6df76a56bb70c598977c3/classes/MATHRequired.md) when the browser encoding is UTF-8, you get the '?' symbol. (I think the file is in the Windows-1252 encoding.)

**Comment by louisel** [comment]
Ok, changed the relevant files to UTF-8. Turns out dashes (-) are special.

**Comment by lidavidm** [comment]
Alright, thanks for the change! I'll go ahead and merge this now.

Looks like a [Unicode byte order mark](https://en.wikipedia.org/wiki/Byte_order_mark) snuck into the homepage, which I'll just remove.

**Comment by lidavidm** [comment]
Looks like it's live now. Thanks again!

**Comment by lidavidm** [comment]
Hey Louise, I noticed that we never added you to the contributors list, whoops! Would you like to appear, and if so, how would you prefer your name to appear?

**Comment by louisel** [comment]
Yeah that'll be nice. You can put my name down as Louise Lee.

**Comment by lidavidm** [comment]
Thanks, it's now live!

**Pull request merged**
